name: macOS

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: make setup
      run: make setup
      
    - name: make bin/2DSpriteAnimation
      run: make bin/2DSpriteAnimation
    - name: 'export binary'
      uses: actions/upload-artifact@v2
      with:
          name: 2DSpriteAnimation
          path: bin/2DSpriteAnimation
    - name: make clean
      run: make clean

    - name: make bin/2DSpriteAnimation CXX=g++
      run: make bin/2DSpriteAnimation CXX=g++
    - name: make clean
      run: make clean
